stages:
  - build
  - test
  - push
  - deploy
  
check_vars:
  stage: build
  script:
    - echo "CI_REGISTRY: $CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE"
    - echo "CI_REGISTRY_USER: $CI_REGISTRY_USER"
    - echo "CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD"

before_script:
  #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build --tag="$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME" .

test:
  stage: test
  script:
    - docker-compose run simple_app python manage.py test
  
push:
  stage: push
  script: 
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME"

deploy:
  stage: deploy
  script:
    - docker compose pull
    - docker compose down
    - docker compose up -d