stages:
  - build
  - test
  - push
  - deploy-dev
  - deploy-prod
  

before_script:
  #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

#merge requests:
#  stage: merge requests
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#  script:
#    - echo "Only on merge requests ...!"








build:
  stage: build
  only:
    - main
    - dev
    - merge_requests
  script:
    - docker build --tag="$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME" .

test:
  stage: test
  only:
    - main
    - dev
    - merge_requests
  script:
    - docker compose run simple_app python manage.py test

lint:
  stage: lint
  only:
    - merge_requests
  script:
    - docker compose run simple_app pylint simple_app

push:
  stage: push
  only:
    - main
    - dev
  script: 
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME"

deploy_dev:
  stage: deploy-dev
  environment:
    name: dev
  tags:
    - dev
  only:
    - main
    - dev
  script:
    - docker compose pull
    - docker compose down
    - docker compose up -d
    - echo "This job successfuly done..."

deploy_prod:
  stage: deploy-prod
  environment:
    name: prod
  when: manual
  tags:
    - prod
  only:
    - main
  script:
    - docker compose pull
    - docker compose down
    - docker compose up -d
    - echo "This job successfuly done..."